apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  finalizers:
  - finalizers.fluxcd.io
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: app-repo
  namespace: demo-app
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: ssh-key
  timeout: 20s
  suspend: false
  url: ssh://git@github.com/bernardhalas/flux-demo
