apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  finalizers:
  - finalizers.fluxcd.io
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: app-kustomization
  namespace: demo-app
spec:
  force: false
  interval: 1m0s
  path: ./application
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-repo
